### ISSUE TITLE
hardcoded maintenance jobs avoids using specific settings

### ISSUE THREAD

**Issue by Phil-Friderici** [ghoneycutt/puppet-module-puppet#101]
```$purge_old_reports_command``` will not be used if you changed ```$reports_days_to_keep```.
(workaround: remove ```$reports_days_to_keep``` setting and set the days in your own ```$purge_old_reports_command```)

```$dump_database_command``` will not be used if you changed ```$dump_dir```. But you need to use it for the ```purge_old_db_backups``` cron job.
(workaround: make /var/local a symlink pointing to the real destination)

Results when using these settings are quite surprising. You need to read the code to find the workarounds.

Fixing this will break backward compatibility :(

**Comment by ghoneycutt** [comment]
I'm OK with making changes that are not backward compatible for this. I don't like the idea of the symlink, the configuration should just point to where the dump_dir should be and ensure it is there with mkdir_p. If you'd like to send a PR, I'm good with it.

Since we're talking about doing a major version jump though, it should also have anything else that you think should be changed.

**Comment by Phil-Friderici** [comment]
I'll play around with this to see if I can 'build' the cronjobs together out of it's individual pieces.
